### PR TITLE
ci: fix clang tidy errors

### LINKED ISSUE #654: fix clang tidy errors
https://github.com/cieslarmichal/faker-cxx/actions/runs/9528652077/job/26266591173

### PR DESCRIPTION
**Pull request by jackhwalters**
Errors removed, one warning remains, along with other "notes". Didn't know how pedantic you want to be with compiler suppressions. [Here they are](https://github.com/jackhwalters/faker-cxx/actions/runs/10045828087/job/27764050747#step:5:129) run on my fork for your review.

Closes #654.

### CODE REVIEW

**Comment by jackhwalters** [comment]
The [errors persist](https://github.com/cieslarmichal/faker-cxx/actions/runs/10046141523/job/27765075909?pr=827#step:5:131) on the workflows run as part of this PR which is strange.

**Comment by cieslarmichal** [comment]
strange, I don't know why it doesn't work here

**Comment by cieslarmichal** [comment]
just a suggestion: we could seperate those jobs and use command cli instead of some plugins with clang tidy:

https://github.com/taocpp/taopq/tree/main/.github/workflows

**Comment by jackhwalters** [comment]
> just a suggestion: we could seperate those jobs and use command cli instead of some plugins with clang tidy:
> 
> https://github.com/taocpp/taopq/tree/main/.github/workflows

Yes I would rather use the clang-tidy cli than run-clang-tidy.

**Pull request closed without merging**
