### PR TITLE
Add external dependencies option

### LINKED ISSUE #546: suggestion: Add support for external libfmt and google test
Hello, as we are packaging Faker CXX on Conan (PR https://github.com/conan-io/conan-center-index/pull/24018), we actually use external CMake targets for fmt and GTest, instead of consuming the vendorized one in the externals folder.

GTest is officially adopted in CMake and can be included directly:

- https://cmake.org/cmake/help/latest/module/GoogleTest.html

The fmt library has its own CMake support: 

- https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L408

So the idea would be including a new option like `USE_SYSTEM_DEPENDENCIES`, then load all dependencies with `find_package` and linking to their CMake targets.

I could open a PR with the feature in case acceptable.

### PR DESCRIPTION
**Pull request by uilianries**
Add support to use external dependencies instead of vendorized ones. The new CMake option `USE_SYSTEM_DEPENDENCIES`, uses `find_package` to include (mandatory) fmt and gtest. In case that option is enabled, and the compiler has std::format supported, CMake will use the external dependencies, because the user configured it explicitly.

Added a new CI job to validate the configuration.

closes #546

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]
Nice

**Comment by uilianries** [comment]
@cieslarmichal The current error is due -Werror with unused variable:

```
FAILED: CMakeFiles/faker-cxx.dir/src/modules/string/String.cpp.o 
/usr/bin/g++-13  -I/home/runner/work/faker-cxx/faker-cxx/include -isystem /home/runner/.conan2/p/b/fmt808a6edee61f6/p/include -m64 -O3 -DNDEBUG -std=c++20 -Wall -Wextra -Wpedantic -Wconversion -Wformat -Werror -MD -MT CMakeFiles/faker-cxx.dir/src/modules/string/String.cpp.o -MF CMakeFiles/faker-cxx.dir/src/modules/string/String.cpp.o.d -o CMakeFiles/faker-cxx.dir/src/modules/string/String.cpp.o -c /home/runner/work/faker-cxx/faker-cxx/src/modules/string/String.cpp
In file included from /usr/include/c++/13/map:62,
                 from /home/runner/work/faker-cxx/faker-cxx/include/faker-cxx/String.h:4,
                 from /home/runner/work/faker-cxx/faker-cxx/src/modules/string/String.cpp:1:
In member function ‘std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_lower_bound(_Link_type, _Base_ptr, const _Key&) [with _Key = char; _Val = std::pair<const char, faker::CharCount>; _KeyOfValue = std::_Select1st<std::pair<const char, faker::CharCount> >; _Compare = std::less<char>; _Alloc = std::allocator<std::pair<const char, faker::CharCount> >]’,
    inlined from ‘std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::find(const _Key&) [with _Key = char; _Val = std::pair<const char, faker::CharCount>; _KeyOfValue = std::_Select1st<std::pair<const char, faker::CharCount> >; _Compare = std::less<char>; _Alloc = std::allocator<std::pair<const char, faker::CharCount> >]’ at /usr/include/c++/13/bits/stl_tree.h:2532:36,
    inlined from ‘std::map<_Key, _Tp, _Compare, _Alloc>::iterator std::map<_Key, _Tp, _Compare, _Alloc>::find(const key_type&) [with _Key = char; _Tp = faker::CharCount; _Compare = std::less<char>; _Alloc = std::allocator<std::pair<const char, faker::CharCount> >]’ at /usr/include/c++/13/bits/stl_map.h:1220:25,
    inlined from ‘static std::string faker::String::generateStringWithGuarantee(faker::GuaranteeMap&, std::set<char>&, unsigned int)’ at /home/runner/work/faker-cxx/faker-cxx/src/modules/string/String.cpp:96:37:
/usr/include/c++/13/bits/stl_tree.h:1952:9: error: ‘item’ may be used uninitialized [-Werror=maybe-uninitialized]
 1952 |         if (!_M_impl._M_key_compare(_S_key(__x), __k))
      |         ^~
In file included from /home/runner/work/faker-cxx/faker-cxx/src/modules/string/String.cpp:9:
/home/runner/work/faker-cxx/faker-cxx/include/faker-cxx/Helper.h: In static member function ‘static std::string faker::String::generateStringWithGuarantee(faker::GuaranteeMap&, std::set<char>&, unsigned int)’:
/home/runner/work/faker-cxx/faker-cxx/include/faker-cxx/Helper.h:92:11: note: ‘item’ was declared here
   92 |         T item;
      |           ^~~~
cc1plus: all warnings being treated as errors
```

Not sure what best approach here, it could ignore Werror (remove from CMake), ignore that specific error (add pragma in String.cpp), or fixing it in the code (I don't know should be fixed in that case.

**Comment by cieslarmichal** [comment]
I think we can disable werror flag.

**Comment by uilianries** [comment]
@cieslarmichal Done, without -Werror everything passed.

**Review by cieslarmichal — APPROVED** [review]

**Pull request merged**
