### PR TITLE
V0.1.0

### PR DESCRIPTION
**Pull request by mykulyak**

### CODE REVIEW

**Comment by mykulyak** [comment]
My fault, sorry for inconvenience.

**Comment by cieslarmichal** [comment]
hello, what happened, why did you close PR? :)

**Comment by mykulyak** [comment]
Hey @cieslarmichal ,

Short answer - this PR should've been done to the forked repo :)

Long answer - a week ago I created a fork of your project ([reasons](https://github.com/mykulyak/faker/wiki)). I believe changes I did in the fork would be beneficial for the original project as well. If you're open to making breaking changes, we can even think about merging my fork back.

**Comment by cieslarmichal** [comment]
Hello, I am open to breaking changes, everything seems good, you can raise a PR to my repo and make it v1 version

**Comment by cieslarmichal** [comment]
You did a good job there, one thing I am not sure is removing github actions, how the end user could use it (lets say on linux without vcpkg)?

**Comment by cieslarmichal** [comment]
I think giy submodules are easy to use and thats the main reason I used them, but maybe I am lacking some knowledge about how it can be used easy as well

**Comment by cieslarmichal** [comment]
I will be happy if you decide to contribute this :)

**Comment by mykulyak** [comment]
@cieslarmichal, 

> I am not sure is removing git submodules, how the end user could use it (lets say on linux without vcpkg)?

Well, `find_package()` should still work. I'm thinking about the following process:

1. if CMake is supplied with a toolchain file (from `vcpkg`, `Conan`, etc.), it will look for libraries in package manager locations
2. if not, it will look for either:
    a. system-wide dependencies (e.g. those installed by `apt` or `dpkg`)
    b. locally cloned repositories, which can fetched and built using `FetchContent` ([an example](https://cmake.org/cmake/help/latest/module/FetchContent.html#overview))

The main idea behind this flow is to prevent duplication of dependencies, especially in complex projects. Git submodules aren't that flexible.

> I will be happy if you decide to contribute this :)

Great then :) I'll create another PR from [forked repo](https://github.com/mykulyak/faker) later this week.

**Pull request closed without merging**
