### PR TITLE
added bosnia names #300 

### PR DESCRIPTION
**Pull request by ahronSteinbruch**

### CODE REVIEW

**Comment by cieslarmichal** [comment]
Rename data/Bosnia to data/bosnia

**Comment by ahronSteinbruch** [comment]
i fix the folder name  I changed it before but the git is not case sensitive

**Comment by cieslarmichal** [comment]
Now I can see two bosnian data directory 😁 one with lower one with upper

**Comment by cieslarmichal** [comment]
Also please resolve conflicts

**Pull request closed without merging**
