### PR TITLE
Food Module is Added.

### PR DESCRIPTION
**Pull request by yakupcemilk**
**Food module done with some extra content.** 

You can use in your code with this:
`Food::dishName()`
of course you can change the submodule.

I want to update it, so if you suggest any kind of "food" things I'll be thankfull for that. And I'm preparing another thing for Faker Cxx but Michal wants to add the food module firstly. Thanks again for this library.

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]
Nice one! Good job :fire:

**Comment by yakupcemilk** [comment]
Can I design an algorithm for developing the Faker Cxx easier?

**Comment by cieslarmichal** [comment]
Sure, go ahead :) 
Would you like to join our discord so we can communicate easier?

**Comment by yakupcemilk** [comment]
Yes! Thank you Michal

**Comment by yakupcemilk** [comment]
and actually I'm a member of your discord server

**Pull request merged**
