### PR TITLE
chore: Added new e-sport module to be implemented (#768)

### PR DESCRIPTION
**Pull request by Mehdibenhadjkhelifa**
Added the e-sport module boilerplate code as requested. Although i don't know if the implementations were part of the request . Also changed cmake under /src to include both .cpp and .h files. If more work regarding this task is needed just let me know. Cheers !
Edit: Checks failed, probably because i forgot to export the functions and include them in the /include directory. I'm working on it.

### CODE REVIEW

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
Yup, implementation should be included with tests, also add doxygen comments in header

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
use Esport/esport not E-sport/e-sport

**Comment by cieslarmichal** [comment]
hey are you working on this or should I close a PR?

**Comment by Mehdibenhadjkhelifa** [comment]
Hey, I'm not currently working on it no. if someone else wants to take the job let them have it.

**Comment by cieslarmichal** [comment]
Ok

**Pull request closed without merging**
