### PR TITLE
feat: Add location addresses data from Korea #445

### PR DESCRIPTION
**Pull request by GitKimUser**
- Update location.cpp
- Update location_data.h
- Update location_test.cpp

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
why did you add some submodule? please remove

**Comment by GitKimUser** [comment]
> why did you add some submodule? please remove

image
do I have to remove all of the submodule?

**Comment by GitKimUser** [comment]
> Looks like you added faker-cxx as submodule, look in PR changes

image
I think that ./faker-cxx/faker-cxx is the directory that makes problem.. right??

**Comment by cieslarmichal** [comment]
Yes try to delete it from changes

**Comment by cieslarmichal** [comment]
also resolve conflicts

**Comment by cieslarmichal** [comment]
I would try this: https://stackoverflow.com/questions/65215051/how-to-pull-the-changes-from-main-branch-to-forked-branch - it should work, if not join our discord channel and we will help you

**Comment by GitKimUser** [comment]
> I would try this: https://stackoverflow.com/questions/65215051/how-to-pull-the-changes-from-main-branch-to-forked-branch - it should work, if not join our discord channel and we will help you

I saw the contents of the stackoverflow you provided and tried it. I made several commitments, but I forgot to push it, so I pushed it all at once. I wonder if the conflict has been resolved about the changes.

**Review by cieslarmichal — APPROVED** [review]

**Comment by cieslarmichal** [comment]
test for koea fails: LocationTest.shouldGenerateKoreaStreet
also run clang format

**Comment by GitKimUser** [comment]
> test for koea fails: LocationTest.shouldGenerateKoreaStreet also run clang format

image
I've tried building and ctest without any code modification at the moment, but it passed with the screenshot. Is it irrelevant to the error above regarding this test??

**Comment by cieslarmichal** [comment]
I have merged main branch into yours here, you can try fetching it and trying to run tests

**Comment by GitKimUser** [comment]
> I have merged main branch into yours here, you can try fetching it and trying to run tests

image

You mean the process of this screenshot, right? If so, when I ran the ctest again, it said that it didn't fail.

**Pull request closed without merging**
