### PR TITLE
Persian names

### PR DESCRIPTION
**Pull request by alisedighmoghadam**
Hello there, I added the Persian names to the project. Since I needed to use UTF8 encoding for Persian and Arabic characters, I made a function in string helper to convert wstring to string. Also, I hardcoded the Persian names as wstring and then by using my function I converted them to string and passed them to PeopleNames. 

This is my first time contributing to this project, so I would appreciate it if you check my code and let me know if there are any problems or questions.

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]
Very good, nice!

**Comment by alisedighmoghadam** [comment]
Sure I'll fix it.

**Comment by cieslarmichal** [comment]
Stil failing

**Comment by alisedighmoghadam** [comment]
I haven't worked on it yet I just need some time to work on it. I’ve only added the locale header.

**Comment by cieslarmichal** [comment]
Ok, no problem

**Pull request merged**
