### PR TITLE
refactor: add locale to animal module

### PR DESCRIPTION
**Pull request by Fictionistique**
Fixes issue #888 
Adds locale to the animal module

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]

**Comment by Fictionistique** [comment]
Could you please add a "hacktoberfest-accepted" label to the PR?

**Comment by cieslarmichal** [comment]
What? 😁 Why?

**Comment by Fictionistique** [comment]
I would appreciate it as it would count towards my hacktoberfest contributions.

**Comment by cieslarmichal** [comment]
added

**Comment by Fictionistique** [comment]
Thank you so much!

**Pull request merged**
