### PR TITLE
Issue#452

### PR DESCRIPTION
**Pull request by jomorodi**
The CMakeLists.txt was modified because Ubuntu 22.04 version had gcc version 11 which did not have the <format> header and did not compile on my machine so i changed the conditional to allow for it to use the fmt::format library 
The modification lead to updating the FormatHelper.h header to reflect the changes. in addition The fmt library was also added as dependency to the test target to enable the test compile on my machine
Estonia locaction data was added which includes EstoniaAddresses EstoniaCounties EstoniaStreetNames EstoniaStreetSuffixes
> test was appended to the end of LocationTest using the test for denmark as a template
> estonia was included in AddressCountry enum
> finally, The estonia data was gotten from resource available on the internet and google maps so their is no guarantee that all the information are correct as i do not live in estonia. "  
[issue#452 1be61dd] introduction of estonian location data The CMakeLists.txt was modified because Ubuntu 22.04 version had gcc version 11 which did not have the <format> header and did not compile on my machine so i changed the conditional to allow for it to use the fmt::format library The modification lead to updating the FormatHelper.h header to reflect the changes. in addition The fmt library was also added as dependency to the test target to enable the test compile on my machine Estonia locaction data was added which includes EstoniaAddresses EstoniaCounties EstoniaStreetNames EstoniaStreetSuffixes test was appended to the end of LocationTest using the test for denmark as a template estonia was included in AddressCountry enum finally, The estonia data was gotten from resource available on the internet and google maps so their is no guarantee that all the information are correct as i do not live in estonia.

Kind regards

### CODE REVIEW

**Comment by cieslarmichal** [comment]
Hello, good job! Please give a star to the repository to make the project more popular :fire:

**Comment by cieslarmichal** [comment]
Please fix failing pipelines

**Review by cieslarmichal — APPROVED** [review]

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
I think its wrong, msvc and clang supports std::format, you could specify it for some version of clan less than

**Comment by cieslarmichal** [comment]
I think clang and msvc should stay the same

**Comment by jomorodi** [comment]
> I think clang and msvc should stay the same

okay i reverted back to the previos commit

**Comment by cieslarmichal** [comment]
Try to add more specified checks in format helper like defined(__GNUC__) && less than 12

**Comment by cieslarmichal** [comment]
Looks like in clang and msvc this if resolves to true and it tries to use fmt

**Comment by cieslarmichal** [comment]
Btw cant you install g++ 13? 😁

**Comment by jomorodi** [comment]
> Try to add more specified checks in format helper like defined(**GNUC**) && less than 12
ah ok i see the bug  now.

**Comment by cieslarmichal** [comment]
((defined(__GNUC__) && (__GNUC__ < 12)  && !defined(__clang__)) should work :smile:

**Comment by jomorodi** [comment]
looks like  clang also defines gnuc

**Comment by jomorodi** [comment]
> Btw cant you install g++ 13? 😁

reason is i would need to use a third party ppa but  i am trying to avoid any possible breaks on my OS. in addition , too lazy to manually compile the compiler . i do not understand the error message coming from  msvc workflow i have not modified any of those document in this current branch. it could be an old issue

**Comment by cieslarmichal** [comment]
I know about msvc issue, if clang build will pass I will merge it :)

**Review by cieslarmichal — APPROVED** [review]

**Comment by cieslarmichal** [comment]
Issue is mentioned here: https://github.com/cieslarmichal/faker-cxx/issues/469

**Pull request merged**
