### PR TITLE
Issue #126 Add location addresses data from Argentina

### PR DESCRIPTION
**Pull request by darksoul96**
Hi, this is my first time here and I saw that address info from Argentina was not done yet.
Please feel free to give feedback, I'm kind of new to creating pull requests.

Kind regards.

### CODE REVIEW

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
Nice, but you need to add them to location.cpp and locationtest.cpp as well in order to make it working :)

**Comment by darksoul96** [comment]
Hi Michal! Thanks for replying. 
How should I proceed now? Should I just make another pull request with changes in location.cpp and locationtest.cpp?

**Comment by cieslarmichal** [comment]
Hello, you can just commit and push to this PR :)

**Review by cieslarmichal — APPROVED** [review]
Looks good!

**Pull request merged**
