### PR TITLE
Number improvements

### PR DESCRIPTION
**Pull request by dario-loi**
# Changes

## `Number` Performance Improvements

After observing that `Number` initialized a mersenne twister and random generator on the stack on each call of the function `integer`, I moved them out of the function and stored them as a statically-initialized member of the `Number` class, this improves performance by skipping the initialization of these objects whenever a number is generated, meaning that the performance of `integer` is now closer to what one would get by directly using the standard library, a worthwhile improvement considering that `Number` is also used as a helper in other modules.

## `Number` Type Safety

Changed the `Number` module to be header-only, this allows us to make the class a template that can work with any integral type. Through concepts we can constrain the templated type `T` to be of type `std::integral`, while allowing the user to generate a wider range of numbers from the same interface, such as `unsigned int`s, `size_t`s, etc... One immediate benefit of this is that in the `Helper` module we are now able to index the whole theoretical range of a `std::vector`, by generating a `size_t` instead of an `int`.

## Quality-of-Life changes

Swapped the order of `integer`'s arguments, it makes much more sense to have `min` come before `max`. The "max by default" behavior is provided by an overload that accepts a single parameter and correctly calls the two-arguments function, check `Number.h` to see what I mean. All tests have been changed accordingly (the order of parameters has been swapped to the sensible one) and a test has been added to check that the overload is correctly resolved.

### CODE REVIEW

**Comment by cieslarmichal** [comment]
Good job, it's nice that you started writing documentation, I need to start writing it too :D 
That performance improvement with numbers is really good :)
Do you have anything you would like to work on next?
I will prepare some ultimate TODO list but for now maybe generating float numbers?

**Comment by dario-loi** [comment]
Thank you,

it should be easy to provide an interface for Floats that enforces the same type guarantees as integers, do you think it would be worth it to expose an overload that allows one to change the distribution of the underlying random sampler (uniform, gaussian, gamma, binomial, etc...)?

I could also do that pretty easily while still preserving the easy defaults that we have now, requiring only the bounds and defaulting to the uniform distribution. Do you think the added complexity is worth it?

**Comment by cieslarmichal** [comment]
I think it's worth it to have a possibility to choose underlying random sampler, good idea.
About float generation it could be implemented in similar way with template std::floating_point and uniform_real_distribution.
We need to think about a name for float() function, because we cannot name it float - its reserved keyword. Do you have any idea how to name it? I am thinking about renaming integer to integerNumber() and naming float floatNumber(), what do you think about that?

**Comment by dario-loi** [comment]
I got some work on my fork, but it is highly unstable, I called it `decimal`, a more mathematical term but it is short and not reserved.

As soon as it is stable enough I will add tests and PR the branch again.

**Comment by cieslarmichal** [comment]
Ok, sounds good, I created a repository discussion so we could chat there about features in progress :)

**Comment by cieslarmichal** [comment]
I created a simple TODO list in discussion:
https://github.com/cieslarmichal/faker-cxx/discussions/4
Please add your ideas for next steps if you have any,
Generally speaking - we are cloning https://fakerjs.dev/api/ functionalites.

**Pull request merged**
