### PR TITLE
feat: added `ordinalDirection` generation function

### PR DESCRIPTION
**Pull request by BAKAJ77**
- Implemented random ordinal direction generation function.
- Added testing code for the ordinal direction generation function.

### CODE REVIEW

**Comment by BAKAJ77** [comment]
The changes made in this pull request are aimed to solve this [issue](https://github.com/cieslarmichal/faker-cxx/issues/939).

**Review by cieslarmichal — CHANGES_REQUESTED** [review]
Fix formatting

**Comment by cieslarmichal** [comment]
run clang format

**Comment by BAKAJ77** [comment]
I keep getting this error when I run the script:
```
YAML:43:15: error: invalid boolean
SortIncludes: CaseInsensitive
              ^~~~~~~~~~~~~~~
Error reading <Path>/.clang-format: invalid argument
```

**Comment by cieslarmichal** [comment]
What clang format version do you have?

**Comment by BAKAJ77** [comment]
Nevermind, I re-downloaded the clang-format executable and now it works

**Comment by BAKAJ77** [comment]
@cieslarmichal I think that should do it for the formatting, double checked just to make sure.

**Review by cieslarmichal — APPROVED** [review]

**Pull request merged**
