### PR TITLE
refactor words

### PR DESCRIPTION
**Pull request by Andersama**
Use `std::string_view` where possible except for `words()`. Avoid allocating and shuffling data! Adding a header to combine all data together, organized by length once. Functions rewritten to retrieve by length (binary search) if possible later.

NOTE: check formatting, I use tabs, this library uses spaces, I think I fixed them all.
When initialized all the data structures could be `constexpr` or `constinit`. I brought in a constexpr quicksort (not mine) because `std::sort` is not constexpr until c++20.

### CODE REVIEW

**Review by cieslarmichal — APPROVED** [review]
wow, very nice changes! good job

**Comment by cieslarmichal** [comment]
please fix pipelines :)

**Comment by Andersama** [comment]
Ah, I see the rest of the library depends on how the words module functions. I guess there's more to change hold on.

**Comment by Andersama** [comment]
On second viewing the function that was giving an error was a helper that could be converted to using `std::string_view` as everything else it used has changed, so I rewrote that as well.

**Comment by cieslarmichal** [comment]
/home/runner/work/faker-cxx/faker-cxx/src/modules/word/Word.cpp:23:109: error: ‘length’ is not captured

**Comment by Andersama** [comment]
Always fun forgetting the api, was going to capture length, no need it's passed as the second parameter 🤦. Crossing fingers this should be the last edit.

**Comment by cieslarmichal** [comment]
```/home/runner/work/faker-cxx/faker-cxx/src/modules/word/Word.cpp:24:24: error: cannot convert ‘std::optional<unsigned int>’ to ‘size_t’ {aka ‘long unsigned int’} in initialization``` 😅

**Comment by Andersama** [comment]
Can you tell I don't use optionals much? Ok...last time~

**Comment by Andersama** [comment]
At least now it's failing tests... I think I have it now.

**Review by cieslarmichal — APPROVED** [review]

**Comment by Andersama** [comment]
Also, I'm currently in the process of writing a more universal c++ `sort` function which would work pretty well here. It's MIT licensed so you're welcome to use that instead.

**Pull request merged**
